Update debian directory
Update debian directory from Alban Peignier <alban@tryphon.eu>

diff --git a/debian/rivendell.postrm b/debian/rivendell.postrm
--- a/debian/rivendell.postrm
+++ b/debian/rivendell.postrm
@@ -1,77 +1,65 @@
-#!/bin/sh -e
+#!/bin/sh
+# postrm script for rivendell
+#
+# see: dh_installdeb(1)
 
+set -e
 
-# dh_makeshlibs doesn't add it automaticaly (?!)
-if [ "$1" = "remove" ]; then
-        ldconfig
-fi
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 
 case "$1" in
     purge)
-        # Default values, in case debconf was not used to set them.  These will
-        # be used for system configurations down below after debconf values are
-        # read.
-        # NOTE: make sure to match these defaults with the rivendell.postinst script
-        AUDIOUSER="rduser"
-        AUDIOGROUP="rivendell"
-        AUDIOROOT="/var/snd"
-        REMOVEDATA="false"
+        pkill -x caed || true
+        pkill -x ripcd || true
+        pkill -x rdcatchd || true
 
-        # get debconf entries if used.
-        . /usr/share/debconf/confmodule
-
-        # Is the user configuring with debconf?
-        db_get rivendell/debconfenable || true
-        if [ "$RET" = "true" ]; then
-            db_get rivendell/identity/audioowner || true
-            [ -n ${RET} ] && AUDIOUSER="$RET"
-            db_get rivendell/identity/audiogroup || true
-            [ -n ${RET} ] && AUDIOGROUP="$RET"
-            db_get rivendell/cae/audioroot || true
-            [ -n ${RET} ] && AUDIOROOT="$RET"
-            db_get rivendell/postrm_remove_data || true
-            [ -n ${RET} ] && REMOVEDATA="$RET"
-        fi
-        
         # Remove init.d configuration file
         rm -f /etc/default/rivendell
 
-        # Remove pam_rd hooks from PAM scripts
-        DISPLAY_MANAGER=`cat /etc/X11/default-display-manager`
-        DISPLAY_MANAGER=`basename "$DISPLAY_MANAGER"`
-        dc="/etc/pam.d/$DISPLAY_MANAGER"
-        grep -v "pam_rd.so" "$dc" > "${dc}.dpkg-tmp"
-        mv -f "${dc}.dpkg-tmp" "$dc"
+        rm -f /etc/rd.conf
 
-        # Remove user and group
-        deluser $AUDIOUSER $AUDIOGROUP 2> /dev/null || true
-        deluser $AUDIOUSER 2> /dev/null || true
-        groupdel $AUDIOGROUP 2> /dev/null || true
-        if [ "$REMOVEDATA" = "true" ]; then
-            [ -d "$AUDIOROOT" ] && rm -rf "$AUDIOROOT" || true
-            mysqladmin --force drop Rivendell || true
+        # Remove default asound.conf
+        if [ -f "/etc/asound.conf" ]; then
+            asound_md5sum=`md5sum /etc/asound.conf | cut -f1 -d' '`
+            if [ "$asound_md5sum" = "3cff4df0e438377a63d1caf419b6f347" ]; then
+                rm -f /etc/asound.conf
+            fi
         fi
+        
+        AUDIOGROUP="rivendell"
+        groupdel $AUDIOGROUP > /dev/null 2>&1 || true
+
         [ -d /var/run/rivendell ] && rm -rf /var/run/rivendell || true
         [ -d /var/log/rivendell ] && rm -rf /var/log/rivendell || true
-
-        # Clean out debconf stuff
-        if [ -e /usr/share/debconf/confmodule ]; then
-            . /usr/share/debconf/confmodule
-            db_purge
-        fi
     ;;
 
     remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-        # Nothing to do here
+        pkill -x caed || true
+        pkill -x ripcd || true
+        pkill -x rdcatchd || true
     ;;
 
     *)
-        echo "$0 called with unknown argument \`$1'" >&2
+        echo "postrm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
 
-# NOTE: debhelper section is at the end, so the debconf values can be used during a purge
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
